<a href="https://colab.research.google.com/github/sayahna22/sayahna/blob/master/Tenis_play__Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import pandas as pa
import numpy as np
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.preprocessing import LabelEncoder
import seaborn as sns

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [4]:
data=pa.read_csv("/content/play_tennis.csv")
data.head(5)

day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [21]:
le=LabelEncoder()
data["outlook"]=le.fit_transform(data["outlook"])
data["temp"]=le.fit_transform(data["temp"])
data["humidity"]=le.fit_transform(data["humidity"])
data["wind"]=le.fit_transform(data["wind"])
data["play"]=le.fit_transform(data["play"])
print(data.head(5))
data.isnull().sum()
print(data.shape)

  day  outlook  temp  humidity  wind  play
0  D1        2     1         0     1     0
1  D2        2     1         0     0     0
2  D3        0     1         0     1     1
3  D4        1     2         0     1     1
4  D5        1     0         1     1     1
(14, 6)


In [33]:
x=data.iloc[:,2:6].values
print(x.shape)
y=data['play'].values
print(y.shape)

(14, 4)
(14,)


In [38]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33)
dt=DecisionTreeClassifier()
model=dt.fit(x_train,y_train)
y_pred=model.predict(x_test)



[1 1 0 1 0]


In [43]:
from sklearn import metrics
res=metrics.accuracy_score(y_pred,y_test)
print(res *100)

100.0


In [48]:
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(x_train,y_train)

y_pred=clf.predict(x_test)
print(y_pred)
from sklearn import metrics
res=metrics.accuracy_score(y_pred,y_test)
print(res *100)

[1 1 0 1 0]
100.0


In [51]:
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
model = GaussianNB()

# Train the model using the training sets
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
print(y_pred)
from sklearn import metrics
res=metrics.accuracy_score(y_pred,y_test)
print(res *100)


[1 1 0 1 0]
100.0


In [53]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=3)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
print(y_pred)
from sklearn import metrics
res=metrics.accuracy_score(y_pred,y_test)
print(res *100)



[0 1 1 1 0]
60.0
